config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'

  resources :books do
    post  :like,    on: :member
    put   :take,    on: :member
    put   :return,  on: :member

    resources :comments
  end
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :cover,  CoverUploader

  field :title,           type: String
  field :author,          type: String
  field :description,     type: String
  field :cover,           type: String
  field :status,          type: Boolean,  default: true
  field :likes_count,     type: Integer,  default: 0
  field :rating,          type: Float,    default: 0.0

  belongs_to  :user
  has_many    :likes, dependent: :destroy
  has_many    :comments, dependent: :destroy
  has_many    :history, dependent: :destroy

  validates :title,   presence: true
  validates :author,  presence: true
  validates :description, presence: true

  scope :newest, -> { order_by(created_at: :desc).limit(5) }

  def taken_by(user_id)
    history.where(user_id: user_id, return: nil).exists?
  end
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to  :user
  belongs_to  :book

  validates :body, presence: true

  paginates_per 5
end

app/models/history.rb
class History
  include Mongoid::Document

  field :taken_in,    type: Time
  field :returned_in, type: Time
  field :user_id,     type: String

  belongs_to  :user
  belongs_to  :book
end

app/models/like.rb
class Like
  include Mongoid::Document

  field :rating, type: Integer, default: 0


  belongs_to  :user
  belongs_to  :book

  validates :rating, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :nickname,           type: String
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count, type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  #

  has_many :books
  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # respond_to :html, :js
  before_action :find_book, only: %i[show]

  def new
    @book = Book.new
  end

  def create
    # @book = Book.new(book_params)
    @book = current_user.books.build(book_params)

    if @book.save
      flash[:notice] = 'Book Successful Create!'
      redirect_to book_path(@book)
    else
      respond_to do |format|
        format.js { render 'books/create_errors' }
      end
      # flash[:alert] = @book.errors.full_messages.to_sentence
      # flash[:alert] = 'Image not save'
      # render 'books/modal'
    end
  end

  def edit; end

  def show
    @comments = Comment.order(created_at: :desc).page(params[:page]).per(5)
  end

  def take
    @book.history.create!(user: current_user, taken_in: Time.now)
    @book.update(status: false)
  end

  def return
    @history = @book.history.where(user: current_user, returned_in: nil)
    @history.update(returned_in: Time.now)
    @book.update(status: true)
  end

  def like; end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:cover, :title, :author, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_book

  def index
    @comments = Comment.order(created_at: :desc).page(params[:page])
  end

  def new
    @comment = @book.comments.new
  end

  def create
    @book.comments.create(comment_params).merge(user: current_user)
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :book_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @books = Book.order_by(created_at: :desc)
    @top_books = Book.order_by(created_at: :desc).limit(5)
  end

  def newest
    @books = Book.order_by(created_at: :desc).limit(5)
    render action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/books/_form.html.haml
.new_book_form
  = form_for @book, html: { multipart: true } do |f|
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :author
      = f.text_field :author
    .field
      = f.label :description
      = f.text_field :description
    .field
      = f.label :cover
      = f.file_field :cover

app/views/books/_modal.html.haml
#bookModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Create a new Book
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .create_errors
        = form_for Book.new, remote: true do |f|
          .field
            = f.label :title
            = f.text_field :title, placeholder: 'Book Title'
          .field
            = f.label :author
            = f.text_field :author, placeholder: 'Book Author'
          .field
            = f.label :description
            = f.text_field :description, placeholder: 'Book Description'
          .field
            = f.label :cover
            = f.file_field :cover
          = f.submit 'Create new Book', class: 'btn btn-secondary'

app/views/books/create_errors.js.erb
$('.create_errors').replaceWith("<div class='alert alert-danger w-100'>" +
                                "<%= @book.errors.full_messages.to_sentence %>" +
                                "</div>")

app/views/books/new.html.haml
- content_for :page_title, 'Create a new book'
= render 'form'

app/views/books/show.html.haml
= link_to('Create Book', '#bookModal', 'data-toggle' => 'modal', class: 'nav-link')

.book_title
  = @book.title

%br/
%br/

.row
  .col-6
    - if @book.cover?
      = image_tag @book.cover.thumb.url, class: 'book-cover'
    - else
      = image_tag('cover.jpg', class: 'cover-default')
  .col-6.description
    = @book.description

.rating_container
  .row
    .rating
      %input#star5{:name => "rating", :type => "radio", :value => "5"}/
      %label{:for => "star5", :title => "5"} 5 stars
      %input#star4{:name => "rating", :type => "radio", :value => "4"}/
      %label{:for => "star4", :title => "4"} 4 stars
      %input#star3{:name => "rating", :type => "radio", :value => "3"}/
      %label{:for => "star3", :title => "3"} 3 stars
      %input#star2{:name => "rating", :type => "radio", :value => "2"}/
      %label{:for => "star2", :title => "2"} 2 stars
      %input#star1{:name => "rating", :type => "radio", :value => "1"}/
      %label{:for => "star1", :title => "1"} 1 star

    .likes_counter
      = "Likes: #{@book.likes_count}"
  .comment_link
    = link_to new_book_comment_path(book_id: @book.id), remote: true do
      = "Write comment"

- if @book.status?
  = link_to take_book_path(id: @book.id), method: :put, remote: true do
    %button.btn.btn-success{:type => "button", class: "take_button"} Take
- elsif @book.taken_by(current_user)
  = link_to return_book_path(id: @book.id), method: :put, remote: true do
    %button.btn.btn-warning{:type => "button", class: "return_button"} Return
- else
  %button.btn.btn-danger{:type => "button", class: "status_button"} Taken

#comments
  %table.w-100.text-center
    %thead
      %tr
        %th{ colspan: :'3'} Comments
  - if @book.comments.empty?
    .text-center
      %p
        No Comments yet!
  - else
    .row
      - @book.comments.each do |comment|
        .comment_date.col-2.p-0.text-center
          = comment.created_at.strftime('%v')
          = comment.created_at.strftime('%H:%M:%S')
        .comment_user.col-2.p-0.text-center
          = comment.user.nickname
        .comment_body.col-8.p-0
          = comment.body
= paginate @comments

#history
  %table.w-100.text-center
    %thead
      %tr
        %th.history_title{ colspan: :'3'} History
  - if @book.history.empty?
    .text-center
      %p
        No History yet!
  - else
    %table.w-100.text-center
      %thead
        %tr
          %th
            Taken By
          %th
            Taken In
          %th
            Returned In
      =render @book.history.order_by(taken_in: :desc)

=render 'books/modal'

app/views/books/take.js.erb
$('.take_button').html('<%= j link_to("<i class=\"take_button\"></i>".html_safe, take_book_path(id: @book.id), method: :put, remote: true) %>')

$('.likes_count').html('<%= @book.reload.likes_count %>')
//$('#history').html('<%= render @book.history.order_by(taken_in: :desc)%>')

app/views/comments/_form.html.haml
= form_with model: @comment, url: new_book_comment_path do |f|
  = f.label :comment
  %br
  = f.text_area :body, class: 'w-75' ,rows: '5', placeholder: 'Write You Comment'
  %br
  = f.submit ('Add Comment'),class: 'btn btn-secondary'

app/views/comments/new.js.erb
$('.comment_link a').html("<%= j render 'comments/form' %>");

app/views/dashboard/index.html.haml
.title
  %h3
    ="Books"
  %h3
    - if user_signed_in?
      = link_to ('log out'), destroy_user_session_path, method: :delete
    = link_to ('Edit Profile'), edit_user_registration_path

.top_books
  %h2 Top 5 Books
  %table.table.table-bordered
    %thead
      %tr
        %th Book
        %th Author
        %th{ colspan: :'2' } Status
    %tbody
      - @top_books.each do |book|
        %tr
          %td
            %a{:href => book_path(book)}
              = book.title
          %td
            = book.author
          - if book.status?
            %td In
            %td
              %input{checked: "checked", type: "checkbox", disabled: "disabled"}
          -else
            %td Out
            %td
              %input{:type => "checkbox", disabled: "disabled"}

.book_list
  %h2 All Books
  %table.table.table-boarded
    %thead
      %tr
        %th Book
        %th Author
        %th{ colspan: :'2' } Status
    %tbody
      - @books.each do |book|
        %tr
          %td
            %a{href: book_path(book)}
              = book.title
          %td
            = book.author
          - if book.status?
            %td In
            %td
              %input{checked: "checked", type: "checkbox", disabled: "disabled"}
          -else
            %td Out
            %td
              %input{type: "checkbox", disabled: "disabled"}

-##paginate
  = paginate @comments

app/views/histories/_history.html.haml
%tr
  %td.history_user
    =history.user.nickname
  %td.history_taken
    =history.taken_in.strftime('%v')
  %td.history_returned
    -if history.returned_in.present?
      =history.returned_in.strftime('%v')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Library
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if flash[:notice]
      .alert.alert-success= flash[:notice]
    - if flash[:alert]
      .alert.alert-danger= flash[:alert]
    = yield